cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('remove_from_cart/<str:pk>', views.remove_from_cart, name='remove_from_cart'),
]

store/urls.py
from django.urls import path
from . import views


app_name = 'store'

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('add_to_cart/<str:pk>', views.add_to_cart, name='add_to_cart'),
]

tshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static


urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('profile/', include('user_profile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from . import views


app_name = 'profile'

urlpatterns = [
    path('', views.profile, name='profile'),
]

store/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models
from django.db.models import Sum, F, DecimalField

from phonenumber_field.modelfields import PhoneNumberField


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        """Creates and saves a new user."""
        if not email:
            raise ValueError("Users must have an email address.")
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """Creates and saves a superuser."""
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model with email instead of username and personal info."""

    email = models.EmailField(max_length=120, unique=True)
    name = models.CharField(max_length=200)
    phone = PhoneNumberField()
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, db_index=True, unique=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    photo = models.ImageField(upload_to='products/', blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    
    def __str__(self):
        return self.name


class Entry(models.Model):
    order = models.ForeignKey('Order', related_name='entries', on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f'{self.quantity} ✕ {self.product} for {self.order}'

    @property
    def price(self):
        return self.product.price * self.quantity


class Order(models.Model):
    customer = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE)
    address = models.TextField(max_length=150)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.customer.name} at {self.address}'

    @property
    def total_entries(self):
        return self.entries.count()

    @property
    def total_products(self):
        return self.entries.aggregate(Sum('quantity'))['quantity__sum']

    @property
    def total_price(self):
        return self.entries.aggregate(
            total_price=Sum(F('quantity')*F('product__price'),
            output_field=DecimalField())
        )['total_price']

store/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from allauth.account.forms import SignupForm
from django.http.request import QueryDict

from .models import Order, Category


class OrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields = 'address',
        

class CategoryForm(forms.Form):
    OPTIONS = Category.objects.all().values_list('id', 'name')

    categories = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=OPTIONS,
        label='Categories:',
        initial=Category.objects.all().values_list('id', flat=True),
    )


class StoreSignupForm(SignupForm):
    email = forms.EmailField(max_length=35, label='email')
    name = forms.CharField(max_length=50, label='Full Name')
    phone = PhoneNumberField()

    def save(self, request):
        user = super(StoreSignupForm, self).save(request)
        user.email = self.cleaned_data['email']
        user.name = self.cleaned_data['name']
        user.phone = self.cleaned_data['phone']
        user.save()

        return user

cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from store.forms import OrderForm
from store.models import Entry, Order, Product


@login_required
def cart(request):
    cart = request.session.get('cart', {})
    entries = [Entry(product=Product.objects.get(pk=pk),
                     quantity=cart[pk]) for pk in cart]
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = Order(customer=request.user)
            order.address = form.cleaned_data['address']
            order.save()
            for entry in entries:
                entry.order = order
            Entry.objects.bulk_create(entries)
            messages.add_message(request, 777, f'Thanks for shopping! Your order was created with ID: {order.pk}.')
            request.session['cart'] = {}
            return redirect('profile:profile')
    else:
        data = {'name': request.user.name,
                'phone': request.user.phone}
        form = OrderForm(initial=data)

    total_price = sum(entry.price for entry in entries)
    context = {
        'entries': entries,
        'total_price': total_price,
        'form': form,
        'cart': sum(request.session.get('cart', {}).values()),
    }
    return render(request, 'cart.html', context)


def remove_from_cart(request, pk):
    cart = request.session['cart']
    del cart[pk]
    request.session.modified = True
    return redirect('cart:cart')

    

store/views.py
from django.shortcuts import render, redirect

from .forms import CategoryForm
from .models import Product, Category
from .decorators import force_http


# @force_http
def catalog(request):
    if request.GET:
        form = CategoryForm(request.GET)
        form.is_valid()
        choices = form.cleaned_data['categories']
        request.session['categories'] = choices
        products = Product.objects.filter(category__id__in=choices)
    else:
        if request.session.get('add') and request.session.get('categories'):
            choices = request.session['categories']
            form = CategoryForm({'categories': choices})
            products = Product.objects.filter(category__id__in=choices)
        else:
            if request.session.get('categories'):
                request.session['categories'].clear()
            form = CategoryForm()
            products = Product.objects.all()
        request.session['add'] = False

    context = {
        'products': products,
        'form': form,
        'cart': sum(request.session.get('cart', {}).values()),
    }
    return render(request, 'catalog.html', context)


# @force_http
def add_to_cart(request, pk):
    cart = request.session.get('cart', {})
    cart[pk] = cart.get(pk, 0) + 1
    request.session['cart'] = cart
    request.session['add'] = True
    return redirect('store:catalog')

    

user_profile/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from store.models import Order


@login_required
def profile(request):
    context = {
        'orders': Order.objects.filter(customer=request.user),
        'cart': sum(request.session.get('cart', {}).values()),
    }
    return render(request, 'profile.html', context)

store/templates/cart.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
  {% if entries %}
  <div class="col-10 offset-1">
    <table class="table w-80">
      <thead>
        <tr>
          <th class="h5">Article</th>
          <th class="h5">Quantity</th>
          <th class="h5">Price</th>
        </tr>
      </thead>
      <tbody>
        {% for entry in entries %}
        <tr>
          <th scope="row" class="prodname">{{ entry.product.name }}
            <a href="{% url 'cart:remove_from_cart' entry.product.pk %}" class="del text-danger ml-2">✕</a>
          </th>
          <td>{{ entry.quantity }}</td>
          <td>{{ entry.price }}</td>
        </tr>
        {% endfor %}
      </tbody>
      <tr>
    </table>

    <form method="POST" enctype="multipart/form-data"
      class="d-flex justify-content-between mt-3">
      {% csrf_token %}
      <ul class="list-unstyled mt-2">
        <li>Full Name: <span class="h6">{{ user.name }}</span></li>
        <li class="mt-1">Phone: <span class="h6">{{ user.phone }}</span></li>
      </ul>
      <div class="p-8 ml-3">{{ form|crispy }}</div>
      <div class="p-4 mr-5 pr-5">
        <button type="submit"
          class="btn btn-danger btn-lg float-center align-self-right">Buy for
          ${{ total_price }}
        </button>
      </div>
    </form>

  </div>
  {% else %}
  <div class="col-6 offset-3 mt-4">
    <p class="display-4 mt-5">Your cart is empty</p>
  </div>
  {% endif %}
</div>
	
<script>
$( "th" ).hover(
  function() {
    $('.del').css("visibility", "");
  }, function() {
    $('.del').css("visibility", "hidden");
  }
);
</script>
{% endblock %}

store/templates/catalog.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% load static %}v

{% block content %}

<div class="container position-fixed">
  <form>
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Select</button>
  </form>
</div>

<div class="container">
  <div class="row ml-2">
    <div class="col">
      <div class="d-flex flex-wrap row-hl">
        {% for product in products %}
        <div class="card m-2" style="width:12rem;">
          
          {% if product.photo %}
          <img class="card-img-top" style="object-fit:scale-down; height: 15rem; width: 100%" src="{{ product.photo.url }}">
          {% else %}
          <img class="card-img-top" style="object-fit:scale-down; height: 15rem; width: 100%" src="media/products/not_available.jpg">
          {% endif %}
            
          <div class="card-body d-flex flex-column">
            <h4 class="card-title mb-1">{{ product.name }}</h4>
            <small class="mb-2 text-secondary">{{ product.category }}</small>
            <h6 class="card-text text-bold">${{ product.price }}</h6>
            <p class="card-text pb-auto">{{ product.description }}</p>
            <a href="{% url 'store:add_to_cart' product.pk %}" class="btn btn-warning btn-block mt-auto font-weight-bold">Add to Cart</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

store/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Welcome to T-shop!</title>
	<link rel="stylesheet"
		href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
		integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
		crossorigin="anonymous">
	<link
		href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap"
		rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Questrial&display=swap"
		rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
		rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
		integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
		crossorigin="anonymous"></script>

</head>

<body class="bg-light">
	<nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-3">
		<div class="container">
			<a class="navbar-brand text-warning" href="{% url 'store:catalog' %}">
				<span style="font-family: Permanent Marker, cursive;"
					class="display-4 mr-4">T-shop</span>
				{% if user.is_authenticated %}
				<span class="text-success">Welcome, {{ user.name }}!</span>
				{% endif %}
			</a>

			<ul class="navbar-nav">
				<li class="nav-item mr-2">
					<a class="nav-link text-info" href="{% url 'cart:cart' %}"
						style="font-family: Questrial"><i
							class="material-icons {% if cart %}text-success{% endif %}">shopping_cart</i>
						<span
							class="h5 mx-2 align-text-bottom {% if cart %}text-success{% endif %}">Cart
							({{ cart }})</span></a>
				</li>

				{% if user.is_authenticated %}
				<li class="nav-item mr-2">
					<a class="nav-link text-info" href="{% url 'account_logout' %}"
						style="font-family: Questrial"><i
							class="material-icons">meeting_room</i><span
							class="h5 mx-2 align-text-bottom">Sign out</span></a>
				</li>
				{% else %}
				<li class="nav-item mr-2">
					<a class="nav-link text-info" href="{% url 'account_login' %}"
						style="font-family: Questrial"><i
							class="material-icons">meeting_room</i><span
							class="h5 mx-2 align-text-bottom">Sign in</span></a>
				</li>
				{% endif %}

				<li class="nav-item mr-5">
					<a class="nav-link text-info" href="{% url 'profile:profile' %}"
						style="font-family: Questrial"><i
							class="material-icons">person</i><span
							class="h5 mx-2 align-text-bottom">Profile</span></a>
				</li>

				<!-- <li class="nav-item">
					<a class="nav-link text-info" href="{% url 'admin:index' %}"
						style="font-family: Questrial"><i class="material-icons">assignment_ind</i><span class="h5 mx-2 align-text-bottom">Admin panel</span></a>
				</li> -->

			</ul>
		</div>
	</nav>
	{% block content %}
	{% endblock %}

</body>
</html>

store/templates/profile.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<div class="container m-auto">
  {% if messages %}
    {% for message in messages %}
      {% if message.level == 777 %}
        <div class="alert alert-warning">{{ message }}</div>
      {% endif %}
    {% endfor %}
  {% endif %}
</div>
  
<div class="container">
  <div class="row">
    <div class="col-9 mb-4">
      
      {% if orders %}

      {% for order in orders reversed %}
      <div class="card my-4 border-dark">
        <div class="card-header font-weight-bold">Order #{{ order.pk }} • {{ order.date }}</div>
        <div class="card-body">
          <ul>
            {% for entry in order.entries.all %}
            <li class="card-title">{{ entry.quantity }} ✕ {{ entry.product }} – ${{ entry.price }}</li>
            {% endfor %}
          </ul>
          <tr>
          <p class="ml-4"><mark>
            Total: ${{ order.total_price }}
          </mark></p>
          <h5 class="ml-4 mt-3">Shipping address: <span class="font-weight-normal ml-1">{{ order.address }}</span></h5>
        </div>
      </div>
      {% endfor %}

      {% else %}
      <p class="display-4 mt-5">You have no orders yet</p>
      {% endif %}
        
    </div>
    <div class="col-3">
      <div class="card text-dark bg-wight border-success border-2 mt-4">
        <div class="card-header h4 bg-success text-light">Profile info</div>
        <div class="card-body">
          <p class="card-title">email: <span class="font-weight-bold">{{ user.email }}</span></p>
          <p class="card-title">Full Name: <span class="font-weight-bold">{{ user.name }}</span></p>
          <p class="card-title">Phone: <span class="font-weight-bold">{{ user.phone }}</span></p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}